const { expect } = require("chai");

// Import utilities from Test Helpers
const { BN, expectEvent, expectRevert } = require("@openzeppelin/test-helpers");

/**
 *
 * autogenerated by solidity-visual-auditor
 *
 * execute with:
 *  #> truffle test <path/to/this/test.js>
 *
 * */
const Escrow = artifacts.require(
  "/Users/miriamdong/lighthouse/w11-final/Defi/Blockchain/contracts/Escrow.sol",
);

contract("Escrow", (accounts) => {
  var creatorAddress = accounts[0];
  var firstOwnerAddress = accounts[1];
  var secondOwnerAddress = accounts[2];
  var externalAddress = accounts[3];
  var unprivilegedAddress = accounts[4];
  /* create named accounts for contract roles */

  before(async () => {
    /* before tests */
  });

  beforeEach(async () => {
    this.Escrow = await Escrow.new({ from: creatorAddress });
  });

  it("should revert if ...", () => {
    return Escrow.deployed()
      .then((instance) => {
        return instance.publicOrExternalContractMethod(argument1, argument2, {
          from: externalAddress,
        });
      })
      .then((result) => {
        assert.fail();
      })
      .catch((error) => {
        assert.notEqual(error.message, "assert.fail()", "Reason ...");
      });
  });

  context("testgroup - security tests - description...", () => {
    //deploy a new contract
    before(async () => {
      /* before tests */
      const newEscrow = await Escrow.new();
    });

    beforeEach(async () => {
      /* before each tests */
    });

    it("fails on initialize ...", async () => {
      return assertRevert(async () => {
        await newEscrow.initialize();
      });
    });

    it("checks if method returns true", async () => {
      assert.isTrue(await newEscrow.thisMethodShouldReturnTrue());
    });
  });
});
